# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fb763969cea11f4406a603cde95d0cb54aac81b6de56c428cff7ef4637fe08a6481c0b2f766f5f7c5939cd612ca644a5a5dc5a026f5dd4c58d7b55620c7cbb0

test:
  secret_key_base: b59b9e0f0d6bfa09904f4bbf5858704f1c9fae48b318efe0d514f53f0bc7361ec333f23691afe8fefbb133e12b344027fe7c4d94236f758c44715a06e69cc4b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
